name: Run Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.0.0', '14', '16.0.0', '16', '18.0.0', '18', '20.0.0', '20', '22.0.0', '22', '23.0.0', '23']
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    # Remove this next step when there's a compatible release of dd-trace on npm
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
