name: Run Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.0.0', '18', '20.0.0', '20', '22.0.0', '22', '23.0.0', '23']
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    # Remove this next step when there's a compatible release of dd-trace on npm
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node.js 22
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 22
    # Install just neostandard to avoid installing all dependencies
    - name: Install just neostandard
      run: npm install neostandard@$(node -p "require('./package').devDependencies.neostandard")
    - name: Run lint
      run: npm run lint
