name: Run Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.0.0', '18', '20.0.0', '20', '22.0.0', '22', '23.0.0', '23']
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and run tests
      run: npm it
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    # Install just neostandard to avoid installing all dependencies
    - name: Install just neostandard
      run: npm install neostandard@$(node -p "require('./package').devDependencies.neostandard")
    - name: Run lint
      run: npm run lint
    - name: Check licenses
      run: npm run license-check
